version: '3'

volumes:
  api-db-data:
    driver: local
  keycloak_data:
    driver: local

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    ports:
      - '${API_PORT}:${API_PORT}'
    env_file:
      - .env
    environment:
      PORT: ${API_PORT}
  api-db:
    image: postgres:alpine
    volumes:
      - api-db-data:/var/lib/api-db/data
    ports:
      - 5432:5432
    env_file:
      - .env
  keycloak_db:
    image: postgres
    volumes:
      - keycloak_data:/var/lib/postgres/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8081:8080
    depends_on:
      - keycloak_db
